/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bmo.glb --transform 
Files: bmo.glb [15.67MB] > C:\project\portfolio 3D(react+tw+threejs)\public\models\bmo-transformed.glb [250.21KB] (98%)
Author: Aidan Azorin (https://sketchfab.com/azorin)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/bmo-876ccbeb669a4fb3956cc1bbb936b3a9
Title: BMO
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function BMO(props) {
  const { nodes, materials } = useGLTF("/models/bmo-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.BMO_Big_002initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/bmo-transformed.glb");
